config/routes.rb
require "heartbeat/application"

Rails.application.routes.draw do
  mount Heartbeat::Application, at: "/heartbeat"

  namespace :admin do
    root 'application#index'

    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end
  end

  namespace :api do
    namespace :v2 do
      mount API::V2::Tickets, at: "/projects/:project_id/tickets"
    end

    scope path: "/projects/:project_id", as: "project" do
      resources :tickets
    end
  end

  devise_for :users
  root "projects#index"

  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  resources :attachments, only: [:show, :new]
end

app/models/state.rb
class State < ActiveRecord::Base
  def self.default
    find_by(default: true)
  end

  def make_default!
    State.update_all(default: false)
    update!(default: true)
  end

  def to_s
    name
  end
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < Admin::ApplicationController
  def index
    @states = State.all
  end

  def new
    @state = State.new
  end

  def create
    @state = State.new(state_params)
    if @state.save
      flash[:notice] = "State has been created."
      redirect_to admin_states_path
    else
      flash.now[:alert] = "State has not been created."
      render "new"
    end
  end

  def make_default
    @state = State.find(params[:id])
    @state.make_default!

    flash[:notice] = "'#{@state.name}' is now the default state."
    redirect_to admin_states_path
  end

  private

    def state_params
      params.require(:state).permit(:name, :color)
    end
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.erb
<%= simple_form_for [:admin, state] do |f| %>
  <%= f.input :name %>
  <%= f.input :color %>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/admin/states/index.html.erb
<header>
  <h1>States</h1>

  <ul class="actions">
    <li><%= link_to "New State", new_admin_state_path, class: "new" %></li>
  </ul>
</header>

<ul id="states">
  <% @states.each do |state| %>
    <li>
      <%= render "states/state", state: state %>
      <% if state.default? %>
        (Default)
      <% else %>
        <%= link_to "Make Default", make_default_admin_state_path(state) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/admin/states/new.html.erb
<header>
  <h1>New State</h1>
</header>

<%= render "form", state: @state %>